# permissions for end users to view azurepolicyexemptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: policy-operator
    app.kubernetes.io/managed-by: kustomize
  name: azurepolicyexemption-viewer-role
rules:
- apiGroups:
  - governance.platform.io
  resources:
  - azurepolicyexemptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - governance.platform.io
  resources:
  - azurepolicyexemptions/status
  verbs:
  - get
