# permissions for end users to edit azurepolicyassignments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: policy-operator
    app.kubernetes.io/managed-by: kustomize
  name: azurepolicyassignment-editor-role
rules:
- apiGroups:
  - governance.platform.io
  resources:
  - azurepolicyassignments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - governance.platform.io
  resources:
  - azurepolicyassignments/status
  verbs:
  - get
