apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "policy-operator.fullname" . }}-manager-role
  labels:
    {{- include "policy-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - governance.platform.io
  resources:
  - azurepolicyassignments
  - azurepolicydefinitions
  - azurepolicyexemptions
  - azurepolicyinitiatives
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - governance.platform.io
  resources:
  - azurepolicyassignments/finalizers
  - azurepolicydefinitions/finalizers
  - azurepolicyexemptions/finalizers
  - azurepolicyinitiatives/finalizers
  verbs:
  - update
- apiGroups:
  - governance.platform.io
  resources:
  - azurepolicyassignments/status
  - azurepolicydefinitions/status
  - azurepolicyexemptions/status
  - azurepolicyinitiatives/status
  verbs:
  - get
  - patch
  - update
