{{- if and (eq .Values.auth.method "envVars") .Values.auth.envVars.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "policy-operator.secretName" . }}
  namespace: {{ include "policy-operator.namespace" . }}
  labels:
    {{- include "policy-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  AZURE_CLIENT_SECRET: {{ .Values.auth.envVars.clientSecret | quote }}
{{- end }}
