{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "policy-operator.serviceAccountName" . }}
  namespace: {{ include "policy-operator.namespace" . }}
  labels:
    {{- include "policy-operator.labels" . | nindent 4 }}
  {{- $annotations := .Values.serviceAccount.annotations }}
  {{- if eq .Values.auth.method "workloadIdentity" }}
  {{- $annotations = merge $annotations (dict "azure.workload.identity/client-id" .Values.auth.workloadIdentity.clientId) }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
