apiVersion: governance.platform.io/v1alpha1
kind: AzurePolicyAssignment
metadata:
  labels:
    app.kubernetes.io/name: policy-operator
    app.kubernetes.io/managed-by: kustomize
  name: require-tags-on-rgs
spec:
  displayName: "Policy operator: Require Cost Center tag on Resource Groups"
  description: "Enforces that all resource groups have a CostCenter tag."
  policyDefinitionRef: require-tag-on-resources
  # scope: "/subscriptions/f2024049-e6cb-4489-9270-6d0d6cd65018"
  scope: "/providers/Microsoft.Management/managementGroups/essity-migration"
  enforcementMode: Default
  notScopes:
    - "/subscriptions/f2024049-e6cb-4489-9270-6d0d6cd65018/resourceGroups/rg-taj"
  parameters:
    tagName: "CostCenter"
  metadata:
    assignedBy: "platform-team"
    category: "Tags"