apiVersion: governance.platform.io/v1alpha1
kind: AzurePolicyAssignment
metadata:
  labels:
    app.kubernetes.io/name: policy-operator
    app.kubernetes.io/managed-by: kustomize
  name: audit-vms-without-disaster-recovery
spec:
  displayName: "Operator Sample - Audit virtual machines without disaster recovery configured"
  description: "Enforces that all resource groups have a CostCenter tag."
  policyDefinitionId: "/providers/Microsoft.Authorization/policyDefinitions/0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56" # Audit virtual machines without disaster recovery configured
  scope: "/subscriptions/f2024049-e6cb-4489-9270-6d0d6cd65018" # sub-lz-sandbox-sbx
  notScopes:
    - "/subscriptions/f2024049-e6cb-4489-9270-6d0d6cd65018/resourceGroups/rg-taj"
  enforcementMode: Default
  identity:
    type: "SystemAssigned"
    location: "westeurope"
  metadata:
    assignedBy: "platform-team"
    category: "Compute"
  exemptions:
    - displayName: "Exempt backstage dev Resource Group"
      description: "Resource group for backstage dev environment is exempt from the policy requirement."
      exemptionCategory: Waiver
      expiresOn: "2026-12-31T23:59:59Z"
      scope: "/subscriptions/f2024049-e6cb-4489-9270-6d0d6cd65018/resourceGroups/rg-backstage-dev"
    - displayName: "Exempt taj Resource Group"
      description: "Resource group for taj environment is exempt from the policy requirement."
      exemptionCategory: Waiver
      expiresOn: "2026-12-31T23:59:59Z"
      scope: "/subscriptions/f2024049-e6cb-4489-9270-6d0d6cd65018/resourceGroups/gemini-poc-env"