apiVersion: governance.platform.io/v1alpha1
kind: AzurePolicyAssignment
metadata:
  labels:
    app.kubernetes.io/name: policy-operator
    app.kubernetes.io/managed-by: kustomize
  name: require-tags-on-rgs
spec:
  displayName: "Require Cost Center tag on Resource Groups"
  description: "Enforces that all resource groups have a CostCenter tag."
  policyDefinitionRef: require-tag-on-resources
  scope: "/subscriptions/f2024049-e6cb-4489-9270-6d0d6cd65018"
  enforcementMode: Default
  # notScopes:
  #   - "/subscriptions/4beecc09-f7ae-4469-a36e-dc5106856da2/resourceGroups/az-104-demo"
  parameters:
    tagName: "CostCenter"
  metadata:
    assignedBy: "platform-team"
    category: "Tags"
  exemptions:
    - displayName: "Exempt Dev Resource Groups"
      description: "Resource groups in the dev environment are exempt from the CostCenter tag requirement."
      exemptionCategory: Waiver
      expiresOn: "2025-12-31T23:59:59Z"
      scope: "/subscriptions/f2024049-e6cb-4489-9270-6d0d6cd65018/resourceGroups/az-104-dev-rg"