apiVersion: governance.platform.io/v1alpha1
kind: AzurePolicyDefinition
metadata:
  labels:
    app.kubernetes.io/name: policy-operator
    app.kubernetes.io/managed-by: kustomize
  name: allowed-locations-policy
  annotations:
    governance.platform.io/import-id: "/subscriptions/f2024049-e6cb-4489-9270-6d0d6cd65018/providers/Microsoft.Authorization/policyDefinitions/f3b1859f349a44a7928ff16f"
    governance.platform.io/import-name: "f3b1859f349a44a7928ff16f"
    governance.platform.io/import-mode: "reconcile"
    # governance.platform.io/import-mode: "observe-only"
spec:
  displayName: "vimal is testing policy"
  description: "this is a test policy"
  policyType: Custom
  mode: Indexed
  metadata:
    category: "platform"
  version: "1.0.0"
  parameters:
    allowedLocations:
      type: Array
      defaultValue:
        - "eastus2"
      metadata:
        displayName: "Allowed locations"
        description: "The list of allowed locations for resources."
        strongType: "location"
  policyRuleJson: |
    {
      "if": {
        "not": {
          "field": "location",
          "in": "[parameters('allowedLocations')]"
        }
      },
      "then": {
        "effect": "audit"
      }
    }
  subscriptionId: "f2024049-e6cb-4489-9270-6d0d6cd65018"
