//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignmentExemptionSpec) DeepCopyInto(out *AssignmentExemptionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignmentExemptionSpec.
func (in *AssignmentExemptionSpec) DeepCopy() *AssignmentExemptionSpec {
	if in == nil {
		return nil
	}
	out := new(AssignmentExemptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignmentExemptionStatus) DeepCopyInto(out *AssignmentExemptionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignmentExemptionStatus.
func (in *AssignmentExemptionStatus) DeepCopy() *AssignmentExemptionStatus {
	if in == nil {
		return nil
	}
	out := new(AssignmentExemptionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignmentIdentity) DeepCopyInto(out *AssignmentIdentity) {
	*out = *in
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]IdentityPermission, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignmentIdentity.
func (in *AssignmentIdentity) DeepCopy() *AssignmentIdentity {
	if in == nil {
		return nil
	}
	out := new(AssignmentIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignmentNonComplianceMessagePerPolicy) DeepCopyInto(out *AssignmentNonComplianceMessagePerPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignmentNonComplianceMessagePerPolicy.
func (in *AssignmentNonComplianceMessagePerPolicy) DeepCopy() *AssignmentNonComplianceMessagePerPolicy {
	if in == nil {
		return nil
	}
	out := new(AssignmentNonComplianceMessagePerPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignmentNonComplianceMessages) DeepCopyInto(out *AssignmentNonComplianceMessages) {
	*out = *in
	if in.PerPolicy != nil {
		in, out := &in.PerPolicy, &out.PerPolicy
		*out = make([]AssignmentNonComplianceMessagePerPolicy, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignmentNonComplianceMessages.
func (in *AssignmentNonComplianceMessages) DeepCopy() *AssignmentNonComplianceMessages {
	if in == nil {
		return nil
	}
	out := new(AssignmentNonComplianceMessages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePolicyAssignment) DeepCopyInto(out *AzurePolicyAssignment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePolicyAssignment.
func (in *AzurePolicyAssignment) DeepCopy() *AzurePolicyAssignment {
	if in == nil {
		return nil
	}
	out := new(AzurePolicyAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzurePolicyAssignment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePolicyAssignmentList) DeepCopyInto(out *AzurePolicyAssignmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzurePolicyAssignment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePolicyAssignmentList.
func (in *AzurePolicyAssignmentList) DeepCopy() *AzurePolicyAssignmentList {
	if in == nil {
		return nil
	}
	out := new(AzurePolicyAssignmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzurePolicyAssignmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePolicyAssignmentSpec) DeepCopyInto(out *AzurePolicyAssignmentSpec) {
	*out = *in
	if in.NotScopes != nil {
		in, out := &in.NotScopes, &out.NotScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(AssignmentIdentity)
		(*in).DeepCopyInto(*out)
	}
	if in.NonComplianceMessages != nil {
		in, out := &in.NonComplianceMessages, &out.NonComplianceMessages
		*out = new(AssignmentNonComplianceMessages)
		(*in).DeepCopyInto(*out)
	}
	if in.Exemptions != nil {
		in, out := &in.Exemptions, &out.Exemptions
		*out = make([]AssignmentExemptionSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePolicyAssignmentSpec.
func (in *AzurePolicyAssignmentSpec) DeepCopy() *AzurePolicyAssignmentSpec {
	if in == nil {
		return nil
	}
	out := new(AzurePolicyAssignmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePolicyAssignmentStatus) DeepCopyInto(out *AzurePolicyAssignmentStatus) {
	*out = *in
	if in.Exemptions != nil {
		in, out := &in.Exemptions, &out.Exemptions
		*out = make([]AssignmentExemptionStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePolicyAssignmentStatus.
func (in *AzurePolicyAssignmentStatus) DeepCopy() *AzurePolicyAssignmentStatus {
	if in == nil {
		return nil
	}
	out := new(AzurePolicyAssignmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePolicyDefinition) DeepCopyInto(out *AzurePolicyDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePolicyDefinition.
func (in *AzurePolicyDefinition) DeepCopy() *AzurePolicyDefinition {
	if in == nil {
		return nil
	}
	out := new(AzurePolicyDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzurePolicyDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePolicyDefinitionList) DeepCopyInto(out *AzurePolicyDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzurePolicyDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePolicyDefinitionList.
func (in *AzurePolicyDefinitionList) DeepCopy() *AzurePolicyDefinitionList {
	if in == nil {
		return nil
	}
	out := new(AzurePolicyDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzurePolicyDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePolicyDefinitionSpec) DeepCopyInto(out *AzurePolicyDefinitionSpec) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.PolicyRule != nil {
		in, out := &in.PolicyRule, &out.PolicyRule
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePolicyDefinitionSpec.
func (in *AzurePolicyDefinitionSpec) DeepCopy() *AzurePolicyDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(AzurePolicyDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePolicyDefinitionStatus) DeepCopyInto(out *AzurePolicyDefinitionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePolicyDefinitionStatus.
func (in *AzurePolicyDefinitionStatus) DeepCopy() *AzurePolicyDefinitionStatus {
	if in == nil {
		return nil
	}
	out := new(AzurePolicyDefinitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePolicyExemption) DeepCopyInto(out *AzurePolicyExemption) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePolicyExemption.
func (in *AzurePolicyExemption) DeepCopy() *AzurePolicyExemption {
	if in == nil {
		return nil
	}
	out := new(AzurePolicyExemption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzurePolicyExemption) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePolicyExemptionList) DeepCopyInto(out *AzurePolicyExemptionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzurePolicyExemption, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePolicyExemptionList.
func (in *AzurePolicyExemptionList) DeepCopy() *AzurePolicyExemptionList {
	if in == nil {
		return nil
	}
	out := new(AzurePolicyExemptionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzurePolicyExemptionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePolicyExemptionSpec) DeepCopyInto(out *AzurePolicyExemptionSpec) {
	*out = *in
	if in.ResourceSelector != nil {
		in, out := &in.ResourceSelector, &out.ResourceSelector
		*out = new(ExemptionResourceSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePolicyExemptionSpec.
func (in *AzurePolicyExemptionSpec) DeepCopy() *AzurePolicyExemptionSpec {
	if in == nil {
		return nil
	}
	out := new(AzurePolicyExemptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePolicyExemptionStatus) DeepCopyInto(out *AzurePolicyExemptionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePolicyExemptionStatus.
func (in *AzurePolicyExemptionStatus) DeepCopy() *AzurePolicyExemptionStatus {
	if in == nil {
		return nil
	}
	out := new(AzurePolicyExemptionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePolicyInitiative) DeepCopyInto(out *AzurePolicyInitiative) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePolicyInitiative.
func (in *AzurePolicyInitiative) DeepCopy() *AzurePolicyInitiative {
	if in == nil {
		return nil
	}
	out := new(AzurePolicyInitiative)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzurePolicyInitiative) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePolicyInitiativeList) DeepCopyInto(out *AzurePolicyInitiativeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzurePolicyInitiative, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePolicyInitiativeList.
func (in *AzurePolicyInitiativeList) DeepCopy() *AzurePolicyInitiativeList {
	if in == nil {
		return nil
	}
	out := new(AzurePolicyInitiativeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzurePolicyInitiativeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePolicyInitiativeSpec) DeepCopyInto(out *AzurePolicyInitiativeSpec) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]InitiativeParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PolicyDefinitions != nil {
		in, out := &in.PolicyDefinitions, &out.PolicyDefinitions
		*out = make([]PolicyDefinitionReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePolicyInitiativeSpec.
func (in *AzurePolicyInitiativeSpec) DeepCopy() *AzurePolicyInitiativeSpec {
	if in == nil {
		return nil
	}
	out := new(AzurePolicyInitiativeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePolicyInitiativeStatus) DeepCopyInto(out *AzurePolicyInitiativeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePolicyInitiativeStatus.
func (in *AzurePolicyInitiativeStatus) DeepCopy() *AzurePolicyInitiativeStatus {
	if in == nil {
		return nil
	}
	out := new(AzurePolicyInitiativeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExemptionResourceSelector) DeepCopyInto(out *ExemptionResourceSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExemptionResourceSelector.
func (in *ExemptionResourceSelector) DeepCopy() *ExemptionResourceSelector {
	if in == nil {
		return nil
	}
	out := new(ExemptionResourceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityPermission) DeepCopyInto(out *IdentityPermission) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityPermission.
func (in *IdentityPermission) DeepCopy() *IdentityPermission {
	if in == nil {
		return nil
	}
	out := new(IdentityPermission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitiativeParameter) DeepCopyInto(out *InitiativeParameter) {
	*out = *in
	if in.DefaultValue != nil {
		in, out := &in.DefaultValue, &out.DefaultValue
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedValues != nil {
		in, out := &in.AllowedValues, &out.AllowedValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitiativeParameter.
func (in *InitiativeParameter) DeepCopy() *InitiativeParameter {
	if in == nil {
		return nil
	}
	out := new(InitiativeParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyDefinitionReference) DeepCopyInto(out *PolicyDefinitionReference) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyDefinitionReference.
func (in *PolicyDefinitionReference) DeepCopy() *PolicyDefinitionReference {
	if in == nil {
		return nil
	}
	out := new(PolicyDefinitionReference)
	in.DeepCopyInto(out)
	return out
}
