apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apo-policy-definitions
  namespace: argocd
spec:
  project: azure-policy-operator
  source:
    repoURL: https://dev.azure.com/essity-projects/Infrastructure%20Services%20-%20Cloud%20Platform/_git/azure-policy-management
    targetRevision: feat/policy-ops
    path: definitions/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: policy-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false