apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: azure-policy-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/your-org/your-repo.git
        revision: main
        directories:
          - path: path/to/placeholder-one/*
          - path: path/to/placeholder-two/*
  template:
    metadata:
      name: 'apo-{{ .path.basename }}'
    spec:
      project: azure-policy-operator
      source:
        repoURL: https://github.com/your-org/your-repo.git
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: policy-operator-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true