apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: azure-policy-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://dev.azure.com/essity-projects/Infrastructure%20Services%20-%20Cloud%20Platform/_git/azure-policy-management
        revision: feat/policy-ops
        directories:
          - path: policies/assignments/*
          - path: policies/exemptions/*
  template:
    metadata:
      name: '{{ if ge (len .path.segments) 4 }}{{ join "-" (slice .path.segments 1 4) }}{{ else }}{{ join "-" (slice .path.segments 1) }}{{ end }}'
    spec:
      project: azure-policy-operator
      source:
        repoURL: https://dev.azure.com/essity-projects/Infrastructure%20Services%20-%20Cloud%20Platform/_git/azure-policy-management
        targetRevision: feat/policy-ops
        path: '{{ .path.path }}'
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: policy-operator-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true